#pragma once
/**
 * List of fixed seed nodes for the BitFinite main and test networks
 * @generated by contrib/seeds/generate-seeds.py
 *
 * Each string must be numeric IPv4 dot-notation or numeric
 * IPv6 hex notation, followed by a colon and a port.
 *
 * SECURITY: This file was cleared of all BCH seed node IPs.
 * BFX uses DNS seeds (seed-{1,2,3}.bitfinitechain.org) configured
 * in chainparams.cpp, plus any addnode= entries in bitfinite.conf.
 *
 * To add fixed seeds, run contrib/seeds/generate-seeds.py with
 * BFX mainnet node IPs and regenerate this file.
 */
static const SeedSpec6 pnSeed6_main[] = {
    // Add verified BFX mainnet node IPs here as the network grows
    // Example: { "1.2.3.4:19768" },
};

static const SeedSpec6 pnSeed6_test[] = {
    // Add verified BFX testnet node IPs here
};
