#pragma once
/**
 * List of fixed seed nodes for the BitFinite main and test networks
 * @generated by contrib/seeds/generate-seeds.py
 *
 * Each string must be numeric IPv4 dot-notation or numeric
 * IPv6 hex notation, followed by a colon and a port.
 */
static const SeedSpec6 pnSeed6_main[] = {
    { "178.128.22.195:19768" },
    { "188.166.183.29:19768" },
    { "134.209.105.173:19768" },
    { "128.199.227.216:19768" }
};

static const SeedSpec6 pnSeed6_testnet3[] = {
    { "128.199.227.216:29768" }
};
